# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 552da503f4f01611d37ca90e356e99d4803caed6ca9301c8e0535ad0130995579dc35a8769e5ef0e17271d62fc179fb12ceed1df82b28039030f939de1671a5d

test:
  secret_key_base: 355cc51aaf1a5483b1e096d8a9edf6816bab667cfdcc7875e0a3c09741cf1d982937bb17dc73f1ce33b7ce37c7046bc3368aea122771976ddc7c5821866452cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
